#include "gtest/gtest.h"
#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

bool instruction(bool debug=false)
{
  cout << "To run the program using command line:" << endl;
  cout << "cd into build/bin" << endl;
  cout << "and run .\\main" << endl;
  cout << "if with command line then will be like .\\main arg1 arg2" << endl;
  return true;
}


//Lord help me! 
const bool debug = false;

TEST(INSTRUCTION, Instruction)
{
  bool success = instruction(debug);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running instruction.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}
